name = "bear"
version = "1.0.0"

[dependencies]
lustre = ">= 4.2.2"
gleam_pgo = { path = "./forks/pgo" }
fox = { path = "./forks/fox" }
exception = ">= 0.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"
mist = ">= 1.0.0 and < 2.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
nibble = ">= 1.1.1"
lustre_http = ">= 0.5.2 and < 1.0.0"
gleam_fetch = ">= 0.4.0 and < 1.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
aws4_request = ">= 0.1.1 and < 1.0.0"
beecrypt = ">= 0.3.1 and < 1.0.0"
glint = ">= 0.18.1 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
birl = ">= 1.6.1 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
logging = ">= 1.1.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[erlang]
application_start_module = "bear_application"
extra_applications = ["inets", "ssl"]
